name: continuous-integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nuget Packages
      run: nuget restore .\packages.config -PackagesDirectory .\packages\
#    - name: Build Init
#      shell: cmd
#      working-directory: ${{github.workspace}}
#      run: build\build_init.cmd
#    - name: Build Solution
#      shell: cmd
#      working-directory: ${{github.workspace}}
#      run: build\build_verbose.cmd
    - name: Package Artifacts
      working-directory: ${{github.workspace}}
      run: tar -czvf artifact_build.tar.gz ${{github.workspace}}/tools
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./path/to/artifact_build.zip
        asset_name: artifact_build.zip
        asset_content_type: application/zip
