name: continuous-integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

permissions:
  contents: read
  actions: write
  
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nuget Packages
      run: nuget restore .\packages.config -PackagesDirectory .\packages\
    - name: Build Init
      shell: cmd
      working-directory: ${{github.workspace}}
      run: build\build_init.cmd
    - name: Build Solution
      shell: cmd
      working-directory: ${{github.workspace}}
      run: build\build_verbose.cmd
    - name: Archive build artifacts
      run: tar -czf build_artifacts.tar.gz -C ${{github.workspace}}/bin .
  build_driver:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nuget Packages
      run: nuget restore .\packages.config -PackagesDirectory .\packages\
    - name: Build Tools
      shell: cmd
      working-directory: ${{github.workspace}}
      run: build\build_tools.cmd
    - name: Build Driver
      shell: cmd
      working-directory: ${{github.workspace}}
      run: build\build_zdriver.cmd prefast
    - name: Archive build artifacts
      run: tar -czf build_driver_artifacts.tar.gz -C ${{github.workspace}}/bin .      

  release:
    runs-on: windows-latest
    needs: [build, build_driver]
    steps:
    - uses: actions/checkout@v4
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./build_artifacts.tar.gz
        asset_name: build_artifacts.tar.gz
        asset_content_type: application/gzip
    - name: Upload Driver Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./build_driver_artifacts.tar.gz
        asset_name: build_driver_artifacts.tar.gz
        asset_content_type: application/gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
